<#
.SYNOPSIS
    Open a clean contribution PR from this fork (Yonezawa-Akane/TimeArc) to
    upstream (jerryzhou945/TimeArc:dev), with the fork-local launch scripts
    (run.cmd, launch.cmd) PINNED to upstream's version so the contribution
    carries ZERO launch-script changes.

.DESCRIPTION
    Why this exists: run.cmd / launch.cmd are fork-local (per-machine toolchain
    config). Contributing them straight from `dev` overwrites upstream's copies
    and forces the maintainer to re-fix every time. This script enforces the
    "never contribute launch scripts" rule MECHANICALLY:
      1. branch off origin/dev (all the real work),
      2. git checkout upstream/dev -- run.cmd launch.cmd   (pin -> zero diff),
      3. HARD-VERIFY the launch-script diff vs upstream/dev is empty (abort if not),
      4. commit ONLY those two files, push, and open a PR with EXPLICIT
         --repo / --base / --head so gh never falls into the fork base-repo trap.

.EXAMPLE
    pwsh -File tools/contribute-to-upstream.ps1
    pwsh -File tools/contribute-to-upstream.ps1 -Title "Sync: memo + home art" -NoPr
#>
[CmdletBinding()]
param(
    [string]$Branch = "sync/contribution-$(Get-Date -Format yyyyMMdd)",
    [string]$Title  = "Sync origin/dev -> upstream/dev ($(Get-Date -Format yyyy-MM-dd))",
    [switch]$NoPr
)

$ErrorActionPreference = 'Stop'

# Repo root = parent of the tools/ folder that holds this script (handles spaces).
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$UpstreamRepo = 'jerryzhou945/TimeArc'   # the maintainer / "upper"
$ForkOwner    = 'Yonezawa-Akane'         # gh --head namespace
$BaseBranch   = 'dev'
$PinFiles     = @('run.cmd', 'launch.cmd')

Write-Host "[contribute] Repo: $RepoRoot"

# All git calls go through this wrapper so exit codes are uniformly enforced.
# NB: param is $GitArgs, NOT $args (which is an automatic PowerShell variable).
function Invoke-Git {
    param([Parameter(ValueFromRemainingArguments = $true)] $GitArgs)
    $out = & git -C $RepoRoot @GitArgs
    if ($LASTEXITCODE -ne 0) { throw "git $($GitArgs -join ' ') failed (exit $LASTEXITCODE)" }
    return $out
}

# --- 0. Clean tree gate -- ignore UNTRACKED noise (build logs, .claude, etc.) ---
$dirty = Invoke-Git status --porcelain --untracked-files=no
if ($dirty) {
    throw "[contribute] Working tree has uncommitted TRACKED changes; commit/stash first:`n$dirty"
}

# --- 1. Fetch both remotes (so origin/dev and upstream/dev are current) ---
Write-Host "[contribute] Fetching origin + upstream..."
Invoke-Git fetch origin  | Out-Null
Invoke-Git fetch upstream | Out-Null

# --- 2. Fresh sync branch off origin/dev (NEVER contribute from dev directly) ---
Write-Host "[contribute] Creating branch '$Branch' off origin/dev..."
& git -C $RepoRoot show-ref --verify --quiet "refs/heads/$Branch"
if ($LASTEXITCODE -eq 0) { Invoke-Git checkout $Branch | Out-Null }
else { Invoke-Git checkout -b $Branch origin/dev | Out-Null }

# --- 3. PIN the fork-local launch scripts to upstream/dev (=> zero diff) ---
Write-Host "[contribute] Pinning $($PinFiles -join ', ') to upstream/dev..."
Invoke-Git checkout upstream/dev -- @PinFiles | Out-Null

# --- 4. HARD VERIFY: launch-script diff vs upstream/dev MUST be empty ---
$pinDiff = & git -C $RepoRoot diff --name-only upstream/dev -- @PinFiles
if ($LASTEXITCODE -ne 0) { throw "[contribute] git diff failed; cannot verify the pin invariant." }
if ($pinDiff) { throw "[contribute] ABORT: launch scripts still differ from upstream/dev:`n$pinDiff" }
Write-Host "[contribute] OK: run.cmd/launch.cmd are byte-identical to upstream/dev (zero diff)."

# --- 5. Commit ONLY the pinned files (path-scoped, never -am) ---
$staged = & git -C $RepoRoot diff --cached --name-only
if ($LASTEXITCODE -ne 0) { throw "[contribute] git diff --cached failed." }
if ($staged) {
    Invoke-Git commit run.cmd launch.cmd -m "build: pin fork-local launch scripts to upstream for contribution" | Out-Null
    Write-Host "[contribute] Committed the pin."
} else {
    Write-Host "[contribute] Launch scripts already matched upstream/dev; nothing to commit."
}

# --- 6. Push the sync branch to origin ---
Write-Host "[contribute] Pushing '$Branch' to origin..."
Invoke-Git push -u origin $Branch | Out-Null

# --- 7. Open the PR to upstream, EXPLICIT repo/base/head (avoid gh fork trap) ---
$head = "${ForkOwner}:$Branch"
$body = "Contribution from fork ``$ForkOwner/TimeArc`` -> ``${UpstreamRepo}:$BaseBranch``.`n`n" +
        "Fork-local launch scripts (``run.cmd``, ``launch.cmd``) are PINNED to upstream/dev, " +
        "so this PR carries ZERO launch-script changes by construction. Each fork keeps its " +
        "own per-machine launch scripts; they are never synced upstream.`n`n" +
        "Generated by tools/contribute-to-upstream.ps1."
$ghArgs = @('pr', 'create', '--repo', $UpstreamRepo, '--base', $BaseBranch, '--head', $head, '--title', $Title, '--body', $body)

if ($NoPr) {
    Write-Host "[contribute] -NoPr set. Open the PR with:"
    Write-Host ("  gh " + ($ghArgs -join ' '))
} else {
    Write-Host "[contribute] Opening PR: --repo $UpstreamRepo --base $BaseBranch --head $head"
    & gh @ghArgs
    if ($LASTEXITCODE -ne 0) { throw "gh pr create failed (exit $LASTEXITCODE)" }
}

Write-Host ""
Write-Host "[contribute] DONE. Review the PR on $UpstreamRepo and confirm run.cmd/launch.cmd are NOT in the diff."
